name: Flutter Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload Artifact (APK)
        uses: actions/upload-artifact@v2  # Version 2 is being used here
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          
      - name: Fallback Upload Artifact (using curl)  # Fallback mechanism
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -F "file=@build/app/outputs/flutter-apk/app-release.apk" \
            "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ github.run_id }}/assets?name=app-release_
